### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by Elec332** [PhoenixTeamMC/MTAddon#1]
I do not take credits for these ideas, credits go to @InfinityRaider    
- [x] Ability to change stacksizes.
- [x] Abiltity to change harvestability of blocks.  

Oredict system:
- [x] alpha state  
- [ ] beta state  
- [ ] release state  

MAGICAL SANTA EDIT:
- [ ] Game type forcer

**Comment by SkeletonPunk** [comment]
Ooops, didn't know I could actually click the check boxes.

**Comment by FayeAlephNil** [comment]
Same :P

**Comment by InfinityRaider** [comment]
Neat isn't it, GitHub has some very nice features

**Comment by FayeAlephNil** [comment]
Yes it does

**Comment by Elec332** [comment]
@elifoster 

---

MAGICAL SANTA EDIT:

 Game type forcer

---

I assume you saw my commented-out code ;)

**Comment by elifoster** [comment]
:P I also kind of want to fuck around with it.
